// Contenu séparé : Algèbre — Bases d’algèbre linéaire
window.algebraFolders=[
{title:'1. Quelques structures algébriques',items:[
['def','Définition — Groupe','Un ensemble G muni d’une loi interne * est un groupe si la loi est associative, possède un élément neutre e, et si tout élément possède un symétrique. Si * est commutative, le groupe est abélien.'],
['def','Définition — Sous-groupe','H⊂G est un sous-groupe si e∈H, H est stable par la loi, et tout élément de H possède dans H un symétrique.'],
['def','Définition — Anneau','A muni de + et × est un anneau si (A,+) est un groupe abélien, × est associative, possède un neutre 1A≠0A et est distributive sur +. Il est commutatif si × l’est.'],
['def','Définition — Corps','Un anneau commutatif dans lequel tout élément non nul possède un inverse est un corps commutatif.'],
['def','Définition — Sous-anneau','B⊂A est un sous-anneau si −1A∈B et B est stable par + et ×.'],
['def','Définition — Morphisme d’anneaux','f:A→B est un morphisme si f(1A)=1B, f(x+y)=f(x)+f(y) et f(xy)=f(x)f(y).'],
['def','Définition — Anneau intègre','A est intègre si ∀a,b∈A, ab=0 ⇒ a=0 ou b=0.'],
['def','Définition — Idéal','I⊂A est un idéal si (I,+) est un sous-groupe et ∀a∈A,∀x∈I, ax∈I.'],
['prop','Proposition — Caractérisation des idéaux','I est un idéal ⇔ I est non vide, stable par +, et ∀a∈A,∀x∈I, ax∈I.'],
['prop','Proposition — Le noyau d’un morphisme d’anneaux est un idéal','Pour un morphisme φ:A→B, Ker φ est un idéal de A.'],
['demo','Démonstration — Ker φ est un idéal','On utilise la caractérisation. 1) Kerφ est non vide : φ(0A)=φ(0A+0A)=φ(0A)+φ(0A), donc φ(0A)=0B et 0A∈Kerφ. 2) Si x,y∈Kerφ, φ(x+y)=φ(x)+φ(y)=0B, donc x+y∈Kerφ. 3) Si a∈A et x∈Kerφ, φ(ax)=φ(a)φ(x)=φ(a)0B=0B, donc ax∈Kerφ. Ainsi Kerφ est un idéal.'],
['prop','Proposition — Toute intersection d’idéaux est un idéal','Pour une famille (Ij), l’intersection I=∩Ij est un idéal.'],
['demo','Démonstration — Intersection d’idéaux','0A appartient à chaque Ij donc à I. Si x,y∈I, alors x,y∈Ij pour tout j, donc x+y∈Ij pour tout j et x+y∈I. Si a∈A et x∈I, alors ax∈Ij pour tout j, donc ax∈I.'],
['th','Théorème — Idéal engendré par un élément','Pour a∈A commutatif, {xa | x∈A} est le plus petit idéal contenant a ; on le note (a) ou Aa.'],
['def','Définition — Espace vectoriel','E est un K-espace vectoriel si (E,+) est un groupe et si la loi externe vérifie : (α+β)u=αu+βu, α(u+v)=αu+αv, α(βu)=(αβ)u et 1u=u.'],
['def','Définition — Algèbre associative','Une K-algèbre associative est un K-espace vectoriel muni d’une multiplication bilinéaire associative. Elle est unitaire si elle possède une unité 1.']
]},
{title:'2. Espaces vectoriels et sous-espaces vectoriels — cours + exercices fondamentaux',items:[
['def','Définition — Espace vectoriel, vecteurs, scalaires','Les éléments de E sont les vecteurs, ceux de K les scalaires ; le neutre de (E,+) est le vecteur nul.'],
['exo','Exercice 1 — Loi externe inhabituelle','Pour (x,y)∈R² et λ∈R, on pose λ*(x,y)=(x,λy). Le triplet (R²,+,*) est-il un espace vectoriel ?'],
['corr','Correction — Exercice 1','Non. L’axiome 1·u=u échoue en général : 1*(x,y)=(x,y), mais la distributivité (α+β)*u=α*u+β*u échoue sur la première coordonnée : ((α+β)*(x,y))₁=x tandis que (α*u+β*u)₁=2x. Par exemple pour x=1.'],
['prop','Proposition — Intégrité dans un espace vectoriel','Si αu=0 alors α=0 ou u=0.'],
['demo','Démonstration — Intégrité dans un espace vectoriel','Le sens réciproque est immédiat. Supposons αu=0 avec α≠0. Alors 1/α∈K et (1/α)(αu)=u, tandis que (1/α)0=0. Donc u=0.'],
['def','Définition — Sous-espace vectoriel','F⊂E est un sous-espace si F≠∅, ∀u,v∈F, u+v∈F et ∀α∈K,∀u∈F, αu∈F.'],
['prop','Proposition — Stabilité par combinaisons linéaires','F non vide est un sous-espace ⇔ ∀x,y∈F,∀λ,μ∈K, λx+μy∈F.'],
['demo','Démonstration — Critère de sous-espace par combinaisons linéaires','Si F est un sous-espace, λx et μy sont dans F puis leur somme aussi. Réciproquement, F non vide : prendre x0∈F et λ=1, μ=−1 donne 0∈F ; λ=μ=1 donne la stabilité par addition ; μ=0 donne la stabilité par multiplication scalaire.']
]},
{title:'3. Familles de vecteurs — cours + exercices fondamentaux',items:[
['def','Définition — Sous-espace engendré','Vect(F) est l’ensemble de toutes les combinaisons linéaires finies des vecteurs de F.'],
['def','Définition — Famille génératrice','F est génératrice de E si Vect(F)=E, c.-à-d. tout u∈E est combinaison linéaire des vecteurs de F.'],
['def','Définition — Famille libre / liée','F=(ui) est libre si Σαiui=0 implique que tous les αi sont nuls. Elle est liée s’il existe une relation avec des coefficients non tous nuls.'],
['prop','Proposition — Sous-famille libre / vecteur nul / sur-famille génératrice','Toute sous-famille d’une famille libre est libre ; toute famille contenant 0 est liée ; toute sur-famille d’une génératrice est génératrice.'],
['prop','Proposition — Caractérisation d’une famille liée','Une famille est liée ⇔ au moins un de ses vecteurs est combinaison linéaire des autres.'],
['demo','Démonstration — Famille liée ⇔ un vecteur dépend des autres','Si Σαiui=0 avec un coefficient αn≠0, alors un=Σ(i≠n)(−αi/αn)ui. Réciproquement, si un est combinaison des autres, on ramène tous les termes au même membre et on obtient une relation de liaison non triviale.'],
['method','Méthode — Montrer qu’une famille est libre','Méthode générale : partir de Σαiui=0 et montrer αi=0 pour tout i. Pour des polynômes, exploiter les degrés/coefficients ; une sous-famille d’une base est automatiquement libre.'],
['exo','Exercice 2 — Familles dans R³','On considère a=(1,2,3), b=(4,5,6), c=(2,1,1), d=(1,1,1), e=(3,7,4), f=(−1,0,1), g=(2,0,−2). 1) Indiquer le système à vérifier pour montrer (a,b,c) libre. 2) Pour montrer e∉Vect(c,f). 3) Pour montrer (d,e,f) génératrice de R³. 4) Pour montrer Vect(d,g)⊂Vect(a,b,f). 5) Déterminer toutes les relations de liaison entre a,b,c,d.'],
['corr','Méthode/correction — Exercice 2','1) Résoudre λa+μb+νc=0 et vérifier l’unicité de (0,0,0). 2) Résoudre λc+μf=e et montrer l’absence de solution. 3) Pour (x,y,z) arbitraire, résoudre λd+μe+νf=(x,y,z) et montrer qu’une solution existe pour tout triplet. 4) Il suffit de montrer séparément d∈Vect(a,b,f) et g∈Vect(a,b,f). 5) Résoudre λa+μb+νc+ρd=0 et paramétrer toutes les solutions.'],
['def','Définition — Base et coordonnées','B=(u1,…,un) est une base si elle est libre et génératrice ; alors tout u∈E s’écrit de façon unique u=Σαiui et (α1,…,αn) sont ses coordonnées dans B.'],
['exo','Exercice 3 — Coordonnées dans une base','Dans R³, u=(1,1,1), v=(1,1,2), w=(1,2,3). On admet F=(u,v,w) base. Déterminer les coordonnées de (5,7,12).'],
['corr','Correction — Exercice 3','Chercher λ,μ,ν tels que λu+μv+νw=(5,7,12). Le système donne λ+μ+ν=5, λ+μ+2ν=7, λ+2μ+3ν=12. Donc ν=2, μ=3 et λ=0. Les coordonnées sont (0,3,2).'],
['method','Méthode — Montrer qu’une famille engendre','Montrer E=Vect(F), ou partir d’un u∈E arbitraire et exhiber des coefficients. En dimension n, pour une famille de n vecteurs, libre ⇔ génératrice ⇔ base.'],
['method','Méthode — Montrer qu’un ensemble est un espace vectoriel','Approches du cours : reconnaître un espace engendré ; montrer qu’il est un sous-espace d’un espace connu par stabilité par combinaisons linéaires ; le voir comme noyau d’une application linéaire ; en dernier recours vérifier directement tous les axiomes.'],
['exo','Exercice 4 — Détection d’espaces vectoriels','1) Montrer que An(K), matrices antisymétriques n×n, est un K-espace vectoriel. 2) Montrer que les matrices carrées n×n de trace nulle forment un espace vectoriel. 3) Montrer que F={P∈R4[X] | P(1)=P(2)=0} est un espace vectoriel et en déterminer une base.'],
['corr','Correction — Exercice 4','1) Si Aᵀ=−A et Bᵀ=−B, alors (λA+μB)ᵀ=−(λA+μB) : stabilité par combinaisons linéaires. 2) F=Ker(Tr), car Tr est linéaire ; c’est donc un sous-espace. 3) P(1)=P(2)=0 ⇔ (X−1)(X−2) divise P. Écrire P=(X−1)(X−2)Q avec Q∈R2[X]. Une base est ((X−1)(X−2), X(X−1)(X−2), X²(X−1)(X−2)).'],
['exo','Exercice 5 — Famille génératrice vers système cartésien','Déterminer une équation ou un système d’équations de F=Vect((1,0,1),(3,2,5),(−1,1,0)).'],
['corr','Méthode — Exercice 5','Partir de u=(x,y,z)∈F ⇔ ∃a,b,c, u=a(1,0,1)+b(3,2,5)+c(−1,1,0), puis éliminer a,b,c par équivalences afin d’obtenir les relations portant seulement sur x,y,z.']
]},
{title:'4. Dimension finie et rang — cours + exercices fondamentaux',items:[
['def','Définition — Dimension finie','E est de dimension finie s’il est engendré par une famille finie.'],
['th','Théorèmes — Base incomplète et base extraite','Dans un espace de dimension finie : toute famille libre peut être complétée en une base ; de toute famille génératrice on peut extraire une base.'],
['exo','Exercice 6 — Extraction d’une base','Dans R4 : v1=(1,1,1,1), v2=(0,1,2,−1), v3=(1,0,−2,3), v4=(2,1,0,−1), v5=(4,3,2,1). 1) La famille est-elle libre ? 2) Est-elle génératrice de R4 ? Si oui extraire une base ; sinon déterminer la dimension de son espace engendré.'],
['def','Définition — Dimension','La dimension d’un espace vectoriel de dimension finie est le cardinal d’une (donc de toute) base.'],
['prop','Proposition — Base et cardinalité','Si dim E=n et F est une famille de n vecteurs : F base ⇔ F libre ⇔ F génératrice.'],
['demo','DÉMONSTRATION À SAVOIR — Base et cardinalité','Si F est une base, elle est libre et génératrice. Supposons F libre et card(F)=n=dim E. Par le théorème de la base incomplète, F peut être complétée en une base de E. Mais toute base de E possède n éléments et F en possède déjà n : aucun vecteur ne peut être ajouté, donc F est une base. Supposons F génératrice et card(F)=n. Par le théorème de la base extraite, on peut extraire de F une base B de E. Or card(B)=n et card(F)=n ; comme B⊂F, on a B=F. Donc F est une base.'],
['exo','Exercice 7 — Système cartésien vers une base','F={(x,y,z,t)∈R4 | x+y+z+t=0 et x−y=0}. Deviner dim F, montrer rigoureusement que F est un espace vectoriel, déterminer une base et sa dimension.'],
['corr','Méthode — Exercice 7','Partir de x=y, puis utiliser x+y+z+t=0 pour exprimer les inconnues principales en fonction de deux paramètres libres. Écrire ensuite tout vecteur de F comme combinaison de deux vecteurs, puis vérifier leur liberté.'],
['exo','Exercice 8 — Suites 3-périodiques','F={(un)∈R^N | ∀n, un+3=un}. Deviner la dimension, montrer que F est un espace vectoriel, déterminer une base et sa dimension.'],
['corr','Méthode — Exercice 8','Une suite est entièrement déterminée par u0,u1,u2. Écrire toute suite comme u0e0+u1e1+u2e2, où e0,e1,e2 sont les trois suites 3-périodiques indicatrices des classes modulo 3. Elles sont libres : dim F=3.'],
['def','Définition — Rang','Le rang d’un système est le nombre de pivots d’un système échelonné équivalent. Pour une famille finie F, rg(F)=dim(Vect(F)).'],
['prop','Proposition — Liberté et rang','Pour une famille finie F : F libre ⇔ rg(F)=card(F).'],
['demo','Démonstration — Liberté et rang','Si F est libre, elle est une base de Vect(F), donc rg(F)=card(F). Réciproquement, si rg(F)=card(F), F est une famille génératrice de Vect(F) ayant exactement dim(Vect(F)) vecteurs ; elle en est donc une base, donc elle est libre.'],
['method','Méthode — Montrer qu’une famille est une base','On peut montrer libre + génératrice ; l’unicité de la décomposition ; exploiter rang/dimension ; si card F=dim E, montrer seulement libre ou seulement génératrice ; dans une base de référence, utiliser un déterminant non nul.'],
['exo','Exercice 9 — Détecter des bases','Dire si les familles suivantes sont des bases : 1) ((1,2,1),(1,−1,3),(0,3,−1)) dans R3 ; 2) ((1,−1,1),(1,0,1),(0,1,0)) dans R3 ; 3) ((1,3,2),(−2,1,−1)) dans R3 ; 4) ((0,1,0),(1,2,1),(0,3,1)) dans R3 ; 5) (3,2X,X²−X,2X³−1,−X⁴+X³−2) dans R4[X].']
]},
{title:'5. Opérations sur les sous-espaces — cours + exercices fondamentaux',items:[
['prop','Proposition — Dimension d’un sous-espace','Si E est de dimension finie et F⊂E est un sous-espace, alors dim F≤dim E, avec égalité ⇔ F=E.'],
['demo','Démonstration — Dimension d’un sous-espace','Construire une famille libre dans F et l’agrandir jusqu’à obtenir une base BF de F. Comme BF est aussi libre dans E, card(BF)≤dim E. Si dim F=dim E=n, BF est une famille libre de E à n éléments, donc une base de E ; comme ses vecteurs sont dans F, E⊂F et F=E.'],
['prop','Proposition — Intersection de sous-espaces','Toute intersection de sous-espaces vectoriels de E est un sous-espace vectoriel de E.'],
['prop','Proposition — Produit cartésien','Pour E1,…,Ep espaces vectoriels, ∏Ei est un espace vectoriel. S’ils sont de dimension finie, dim(∏Ei)=Σdim(Ei).'],
['demo','DÉMONSTRATION ANNEXE — Dimension du produit cartésien','Cas p=2. Si (e1,…,en) est une base de E1 et (ε1,…,εm) une base de E2, considérer B=((e1,0),…,(en,0),(0,ε1),…,(0,εm)). Liberté : si Σαi(ei,0)+Σβj(0,εj)=(0,0), alors Σαiei=0 et Σβjεj=0 ; les bases étant libres, tous les coefficients sont nuls. Génération : tout (x,y) s’écrit avec x=Σαiei et y=Σβjεj, donc (x,y)=Σαi(ei,0)+Σβj(0,εj). Ainsi B est une base et dim(E1×E2)=dimE1+dimE2. Pour p>2, récurrence avec E1×…×Ep=(E1×…×Ep−1)×Ep.'],
['def','Définition — Somme F+G','F+G={u+v | u∈F,v∈G}.'],
['exo','Exercice 10 — Égalité de sous-espaces','Soient F,G,H sous-espaces de E tels que F∩G=F∩H, F+G=F+H et G⊂H. Montrer G=H.'],
['corr','Correction — Exercice 10','L’inclusion G⊂H est donnée. Pour H⊂G, soit h∈H. Comme h∈F+H=F+G, h=f+g avec f∈F,g∈G. Alors f=h−g∈H puisque h∈H et g∈G⊂H. Donc f∈F∩H=F∩G, d’où f∈G. Ainsi h=f+g∈G. Donc H⊂G et G=H.'],
['prop','Proposition — Formule de Grassmann','F+G est le plus petit sous-espace contenant F et G. Si F,G sont de dimension finie : dim(F+G)=dimF+dimG−dim(F∩G).'],
['demo','DÉMONSTRATION À SAVOIR — Formule de Grassmann','Soit (e1,…,er) une base de F∩G. Par base incomplète, on la complète en une base (e1,…,er,f1,…,fp) de F et en une base (e1,…,er,g1,…,gq) de G. La famille B=(e1,…,er,f1,…,fp,g1,…,gq) engendre F+G : si x=f+g, développer f dans la base de F et g dans celle de G. Montrons B libre. Si Σαiei+Σβjfj+Σγkgk=0, alors Σβjfj+Σαiei=−Σγkgk appartient à F∩G. Comme (e1,…,er) est une base de F∩G, le membre de gauche peut s’écrire avec les seuls ei. Par unicité dans la base de F, tous les βj sont nuls. De même tous les γk sont nuls, puis les αi sont nuls. B est donc une base de F+G. Ainsi dim(F+G)=r+p+q=(r+p)+(r+q)−r=dimF+dimG−dim(F∩G).']
]},
{title:'6. Sommes directes et supplémentaires — cours + exercices fondamentaux',items:[
['def','Définition — Somme directe','ΣFi est directe si tout vecteur de la somme possède une unique décomposition v=Σui avec ui∈Fi. On note alors ⊕Fi.'],
['prop','Proposition — Caractérisation par le vecteur nul','ΣFi est directe ⇔ (Σui=0 avec ui∈Fi ⇒ tous les ui=0).'],
['demo','Démonstration — Caractérisation par le vecteur nul','(⇒) Si la somme est directe, 0 possède la décomposition 0=0+…+0. Toute autre décomposition 0=Σui doit lui être égale par unicité, donc ui=0. (⇐) Supposons la propriété sur 0. Si v=Σui=Σvi, alors Σ(ui−vi)=0 avec ui−vi∈Fi ; donc ui−vi=0 pour tout i et ui=vi. L’existence est donnée par v∈ΣFi ; la décomposition est donc unique.'],
['prop','Proposition — Somme directe et dimensions','Pour Fi de dimension finie, dim(ΣFi)≤ΣdimFi, avec égalité ⇔ la somme est directe.'],
['demo','DÉMONSTRATION À SAVOIR — Somme directe et dimensions','Pour chaque Fi, choisir une base Bi et juxtaposer toutes ces bases en une famille B. Elle engendre ΣFi : tout vecteur de la somme est somme de vecteurs des Fi, eux-mêmes combinaisons des Bi. Donc dim(ΣFi)≤card(B)=ΣdimFi. Pour l’égalité, considérer φ:∏Fi→ΣFi, φ(u1,…,un)=Σui. Cette application est linéaire et surjective. La somme est directe exactement lorsque Kerφ={0}, donc lorsque φ est injective. Par le théorème du rang, dim(∏Fi)=dimKerφ+dimImφ. Or dim(∏Fi)=ΣdimFi et Imφ=ΣFi. Ainsi dim(ΣFi)=ΣdimFi ⇔ dimKerφ=0 ⇔ Kerφ={0} ⇔ la somme est directe.'],
['prop','Corollaire — Juxtaposition des bases / base adaptée','Si E=F1+…+Fn et Bi est une base de Fi, la juxtaposition B des Bi est une base de E ⇔ la somme est directe.'],
['demo','DÉMONSTRATION — Juxtaposition des bases d’une somme directe','Comme E=F1+…+Fn, la juxtaposition B des bases Bi engendre E. Elle possède ΣdimFi vecteurs. D’après la proposition “somme directe et dimensions”, la somme est directe ⇔ dimE=ΣdimFi. Comme B engendre E, elle est une base exactement lorsque son cardinal vaut dimE. Ainsi somme directe ⇔ B base de E. On peut aussi prouver directement la liberté : une relation linéaire entre les vecteurs de B se regroupe en u1+…+un=0 avec ui∈Fi ; la somme directe impose ui=0, puis la liberté de chaque Bi impose tous les coefficients nuls.'],
['prop','Proposition — Base ⇔ somme directe des droites Kei','B=(e1,…,en) est une base de E ⇔ E=⊕ Kei.'],
['demo','DÉMONSTRATION À SAVOIR — Base ⇔ somme directe des droites engendrées','(⇒) Si B est une base, tout x∈E possède une unique écriture x=Σλiei. Or λiei∈Kei : E=ΣKei et la décomposition est unique, donc E=⊕Kei. (⇐) Si E=⊕Kei, tout x possède une unique décomposition x=Σui avec ui∈Kei. Chaque ui s’écrit de manière unique ui=λiei si ei≠0 ; la directivité exclut ei=0. Ainsi tout x possède une unique écriture x=Σλiei : B est une base.'],
['prop','Proposition — Deux sous-espaces : F+G directe ⇔ F∩G={0}','Pour deux sous-espaces, la somme est directe exactement lorsque leur intersection est réduite à {0}.'],
['demo','DÉMONSTRATION À SAVOIR — F+G directe ⇔ F∩G={0}','(⇒) Soit x∈F∩G. Alors x=x+0=0+x donne deux décompositions de x avec un terme dans F et un dans G. L’unicité impose x=0. Donc F∩G={0}. (⇐) Supposons F∩G={0}. Si f+g=0 avec f∈F,g∈G, alors f=−g appartient à F∩G, donc f=0 puis g=0. Par la caractérisation de la somme directe via le vecteur nul, F+G est directe.'],
['def','Définition — Sous-espaces supplémentaires','F et G sont supplémentaires dans E si E=F⊕G, c.-à-d. tout x∈E possède une unique décomposition x=f+g.'],
['method','Méthode — Montrer que deux sous-espaces sont supplémentaires','Montrer E=F⊕G ; ou montrer existence et unicité de x=f+g ; en dimension finie utiliser F∩G={0} avec dimE=dimF+dimG, ou E=F+G avec la même égalité ; avec des bases, montrer que la juxtaposition d’une base de F et d’une base de G est une base de E.'],
['exo','Exercice 11 — Détecter des supplémentaires','1) Dans C, espace des suites convergentes, montrer que les suites constantes et les suites de limite nulle sont supplémentaires. 2) Montrer Sn(K) et An(K) supplémentaires dans Mn(K). 3) Dans R3[X], P=X³,Q=(X+1)³,R=(X+2)³,S=(X+3)³, F=Vect(P,Q,R), G=R·S : montrer F et G supplémentaires.'],
['corr','Correction — Exercice 11.1','Toute suite convergente u de limite ℓ s’écrit u=(ℓ) +(u−ℓ), somme d’une suite constante et d’une suite tendant vers 0. Si une suite est à la fois constante et de limite 0, sa constante vaut 0 : l’intersection est {0}. Donc C=Constantes⊕S0.'],
['corr','Correction — Exercice 11.2','Pour M∈Mn(K), poser S=(M+Mᵀ)/2 et A=(M−Mᵀ)/2. Alors M=S+A, Sᵀ=S et Aᵀ=−A, donc Mn=Sn+An. Si M∈Sn∩An, Mᵀ=M et Mᵀ=−M, donc 2M=0 et M=0 (sur R ou C). Ainsi Mn=Sn⊕An.'],
['prop','Proposition — Existence d’un supplémentaire','Si E est de dimension finie et F⊂E est un sous-espace, il existe G tel que E=F⊕G. De plus dimE=dimF+dimG.'],
['demo','DÉMONSTRATION À SAVOIR — Existence d’un supplémentaire','Soit (f1,…,fp) une base de F. Par le théorème de la base incomplète, on peut la compléter en une base (f1,…,fp,g1,…,gq) de E. Posons G=Vect(g1,…,gq). La juxtaposition d’une base de F et d’une base de G est précisément une base de E ; par le corollaire sur la juxtaposition des bases, E=F⊕G. Enfin, comme cette base de E contient p+q vecteurs, dimE=p+q=dimF+dimG.'],
['exo','Exercice 12 — Construire un supplémentaire','Dans R4, F={(x,y,z,t) | x+y−z+t=0, x−3y−2z=0}. Déterminer un sous-espace supplémentaire de F dans R4 et sa dimension.'],
['corr','Méthode — Exercice 12','Déterminer d’abord une base de F en résolvant le système, puis compléter cette base en une base de R4. Le sous-espace engendré par les vecteurs ajoutés est un supplémentaire. Sa dimension vaut 4−dimF.']
]},
{title:'7. Feuille de TD — exercices 13 à 39',items:[
['exo','Exercice 13 — Vrai/Faux cours','1) Toute famille contenant une génératrice de E est génératrice. 2) Toute famille contenant une famille libre est libre. 3) Toute famille contenue dans une génératrice engendre E. 4) Toute famille contenue dans une libre est libre. 5) Si (ei)i≤4 est libre, (e1+e2,e2+e3,e3+e4,e4+e1) est-elle libre ? 6) Même question pour (e1+e2,e2+e3,e3+e1) avec (ei)i≤3 libre. 7) Si F libre et u∉VectF, F∪{u} est-elle libre ? 8) Si F⊕G=E et F⊕H=E, a-t-on G=H ?'],
['exo','Exercice 14 — QCM cardinal/dimension','Pour E de dimension n et familles F1,F2 de cardinal m1,m2 : étudier les possibilités m1=n, m1<n, m1>n selon que F1 est libre, liée, génératrice ou base ; étudier les conséquences des inclusions F1⊂F2 ou F2⊂F1 sur liberté/liaison et génération ; enfin étudier les cas m1>n, m1<n, m1=n.'],
['exo','Exercice 15 — Sous-espaces de K[X]','E1={P | degP=3}, E2={P | degP≤3}, E3={P | P′(1)=0}. Dire lesquels sont des sous-espaces de K[X].'],
['exo','Exercice 16 — Sous-espaces de fonctions','Pour a<b, dans R^[a,b] : E1={f surjective}, E2={f | f(a)=3f(b)}, E3={f | f(a)=f(b)+3}. Dire lesquels sont des sous-espaces.'],
['exo','Exercice 17 — Famille exponentielle','Pour N≥1 et n∈[−N,N]∩Z, fn(x)=e^{nx}. Montrer que la famille (fn) est libre.'],
['exo','Exercice 18 — Lemme d’échange','Si (e1,…,en) et (ε1,…,εn) sont deux bases d’un R-espace E, montrer qu’il existe j tel que (e1,…,en−1,εj) soit encore une base.'],
['exo','Exercice 19 — Sous-espace paramétré de R4','F={(a−b+d,2a−d,2b+2c+3d,a+2b−d) | a,b,c,d∈R}. Montrer que F est un sous-espace, déterminer une base et la dimension, puis conclure ce qu’est F.'],
['exo','Exercice 20 — Bases de F,G,F+G','Dans R4 : u1=(1,2,0,1),u2=(2,1,3,1),u3=(7,8,9,5) ; v1=(1,2,1,0),v2=(2,−1,0,1),v3=(−1,1,1,1),v4=(1,1,1,1). F=Vect(u1,u2,u3), G=Vect(v1,…,v4). 1) Bases de F,G,F+G. 2) Dimension de F∩G.'],
['exo','Exercice 21 — Polynômes divisibles par A','A∈Rn[X], A≠0. F={P∈Rn[X] | A divise P}. Montrer que F est un sous-espace, déterminer une base puis un supplémentaire.'],
['exo','Exercice 22 — Polynômes s’annulant en a','Fa={P∈Rn[X] | P(a)=0}. 1) Montrer Fa sous-espace. 2) Montrer (1,(X−a),(X−a)X,…,(X−a)X^{n−1}) base de Rn[X]. 3) Déterminer dim Fa puis un supplémentaire.'],
['exo','Exercice 23 — Supplémentaire dans R3[X]','E=R3[X], F={P∈E | P(0)=0 et P(1)−P′(1)=0}. 1) Montrer F sous-espace. 2) G engendré par les monômes de degré pair : montrer E=F⊕G.'],
['exo','Exercice 24 — Base (X−a)^k','E=R_{2n}[X], Pk=(X−a)^k pour 0≤k≤2n. 1) Montrer (Pk) base de E. 2) Pour b∈R, déterminer les coordonnées de (X−a)^n(X−b)^n dans cette base.'],
['exo','Exercice 25 — Base de S2(R)','A=[[1,−2],[-2,1]], B=[[1,3],[3,6]], C=[[-1,1],[1,−3]]. 1) Montrer qu’elles forment une base de S2(R). 2) Décomposer une matrice symétrique quelconque dans cette base.'],
['exo','Exercice 26 — Dimension de Sn(K)','Déterminer la dimension de l’espace des matrices symétriques n×n.'],
['exo','Exercice 27 — Base de matrices inversibles','Existe-t-il une base de Mn(K) constituée uniquement de matrices inversibles ?'],
['exo','Exercice 28 — Suites arithmétiques','Montrer que l’ensemble des suites arithmétiques est un espace vectoriel de dimension finie et déterminer sa dimension.'],
['exo','Exercice 29 — EDO et espace vectoriel','Déterminer une base et la dimension de F={f∈R^R | f solution de y″−3y′+3y=0}.'],
['exo','Exercice 30 — Somme directe de fonctions','E=C0([−1,1],R). F1={fonctions constantes}, F2={f | f=0 sur [−1,0[}, F3={f | f=0 sur ]0,1]}. Montrer E=F1⊕F2⊕F3.'],
['exo','Exercice 31 — Supplémentaire dans F(R)','Dans E=F(R), déterminer un supplémentaire de F={f | f(0)+f(1)=0}.'],
['exo','Exercice 32 — Rang d’une union','Pour familles finies F,G de E, montrer rg(F∪G)≤rgF+rgG.'],
['exo','Exercice 33 — Rang selon m','Calculer selon m le rang de u=(m,1,1), v=(1,m,1), w=(1,1,m).'],
['exo','Exercice 34 — Inégalité de rang','F famille de n vecteurs de rang r ; G sous-famille de m vecteurs de rang s. Montrer s≥m+r−n.'],
['exo','Exercice 35 — Union de deux sous-espaces','Montrer F∪G sous-espace ⇔ F⊂G ou G⊂F.'],
['exo','Exercice 36 — Sommes directes égales','Ei⊂Fi pour tout i et ⊕Ei=⊕Fi. Montrer Ei=Fi pour tout i.'],
['exo','Exercice 37 — Pot-pourri R4','F={(x,y,z,t)∈R4 | x+2y−z=0, x−y=0, t=0}. 1) Base B de F. 2) Un supplémentaire G. 3) Un autre G′≠G. 4) Pour u=(−2,−2,−6,0), tester u∈F puis coordonnées dans B ou décomposition dans F⊕G. 5) Refaire avec u=(−2,−2,6,0).'],
['exo','Exercice 38 — Polynômes et intégrale','1) F={P∈Rn[X] | ∫_0^1 P(t)dt=0} est-il un espace vectoriel ? 2) Pk=X^k+(2k/(k+1))X−1 : montrer Vect(P1,…,Pn)⊂F. 3) Qu’en déduire ?'],
['exo','Exercice 39 — Formule de Taylor polynomiale','Pour P∈K[X], montrer P(X+1)=Σ_{k≥0} P^{(k)}(X)/k!.']
]}
];
